"""Preflight for the chunk-9B full-history run -- generator for `chunk9b_preflight.md`.

Committed HERE, beside its own output, because CLAUDE.md's git rules (REVIEW_7 finding C3)
require a session making claims from real store data to commit the generating script and its
output under `docs/evidence/`.

    python docs/evidence/chunk9b_preflight.py                 # print the checks
    python docs/evidence/chunk9b_preflight.py --out FILE      # ...and write them down

Read-only and OFFLINE. It opens exactly what the run will open -- both Parquet stores, the
corporate-action day-cache (served at any age; architect 31-Jul-2026), the cached instrument
master, the disclosed-residual register and `config.yaml` -- measures the settled universe and
the minute era FROM THE STORES, and prints one line per check. **If any check fails it does not
emit the run command and exits non-zero.**

The implementation lives in the package at `src/acumen/run_backtest.py`; this file is the
launcher, with the same bare-clone bootstrap the other launchers use (REVIEW_2 F12).

Source files in this repo are ASCII-only on purpose (see src/acumen/config.py).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_OUT = REPO_ROOT / "docs" / "evidence" / "chunk9b_preflight.md"


def _module() -> Any:
    try:
        from acumen import run_backtest
    except ModuleNotFoundError:
        sys.path.insert(0, str(REPO_ROOT / "src"))
        from acumen import run_backtest
    return run_backtest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="chunk-9B run preflight")
    parser.add_argument("--label", default=None, help="run label (default: the module's)")
    parser.add_argument("--symbols", default=None, help="comma-separated subset (smoke path)")
    parser.add_argument("--out", default=None, help="also write the report to this markdown file")
    args = parser.parse_args(argv)

    rb = _module()
    label = args.label or rb.DEFAULT_LABEL
    subset = (
        tuple(part.strip().upper() for part in args.symbols.split(",") if part.strip())
        if args.symbols
        else None
    )
    report = rb.preflight(label=label, symbols_override=subset)
    lines = rb.render_preflight(
        report, label=label, command=rb.run_command(label, subset)
    )
    for line in lines:
        print(line, flush=True)

    if args.out is not None:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        body = [
            "# chunk 9B preflight -- the gate the full-history run must pass",
            "",
            "Generated by `docs/evidence/chunk9b_preflight.py` (implementation:",
            "`src/acumen/run_backtest.py`), committed under CLAUDE.md's evidence rule",
            "(REVIEW_7 finding C3). Regenerate with:",
            "",
            "    python docs/evidence/chunk9b_preflight.py --out docs/evidence/chunk9b_preflight.md",
            "",
            "Every line below is MEASURED from the local stores, read-only and offline. The",
            "universe is read from the disclosed-residual register and the span from the minute",
            "store's own parquet files -- neither is typed anywhere in this repo.",
            "",
            "```",
            *lines,
            "```",
            "",
        ]
        out.write_text("\n".join(body), encoding="utf-8", newline="\n")
        print(f"\nwrote {out}", flush=True)

    return 0 if report.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
