"""How many stored symbol-days carry a 1-minute stamp outside 09:15..15:29? (QUESTIONS.md Q-17)

Committed HERE, beside its own output, because CLAUDE.md's git rules (REVIEW_7 finding C3)
require a session making claims from real store data to commit the generating script and its
output under `docs/evidence/`.

    python docs/evidence/chunk9b_out_of_session.py --out docs/evidence/chunk9b_out_of_session.md

Read-only and OFFLINE: it opens the 1-minute Parquet store and reads two columns.

WHY IT EXISTS. The chunk-9B smoke run died on RELIANCE 2017-04-28 with an `AggregateError` --
one vendor bar stamped 09:14 (25,015 shares) that `aggregate_15min` refuses because it belongs
to no 15-minute bucket, on a day CONTEXT 4.5's gate 2 had deliberately ADMITTED. Gate 2's own
words are that CONTEXT 7-E2 excludes such a candle "at the CANDLE level (drop the stray bar),
not at the day level", so the two layers disagreed. Before changing anything, this measures how
much data the disagreement covers, and which shape it takes: an isolated vendor artefact on a
few symbols, or a market-wide session property.

Source files in this repo are ASCII-only on purpose (see src/acumen/config.py).
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

import pyarrow.compute as pc
import pyarrow.parquet as pq

REPO_ROOT = Path(__file__).resolve().parents[2]

#: CONTEXT 3.1's session, as open-stamped minutes: 09:15 through 15:29 inclusive.
OPEN_MINUTE = 9 * 60 + 15
LAST_MINUTE = 15 * 60 + 29


def _bootstrap():
    try:
        from acumen import backtest, run_backtest
    except ModuleNotFoundError:
        sys.path.insert(0, str(REPO_ROOT / "src"))
        from acumen import backtest, run_backtest
    return backtest, run_backtest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="out-of-session 1-minute stamps, measured")
    parser.add_argument("--data-dir", default=None, help="defaults to config.yaml's data_dir")
    parser.add_argument("--out", default=None, help="write the report to this markdown file")
    args = parser.parse_args(argv)

    bt, rb = _bootstrap()
    from acumen.config import load_config

    data = Path(args.data_dir) if args.data_dir else load_config(include_env=False).path("data_root")
    register = bt.load_residual_register(data / bt.RESIDUAL_LEDGER_RELPATH)
    symbols = rb.settled_symbols(register)
    root = data / "minute_store" / "minute"

    per_symbol: Counter = Counter()
    per_day: dict = defaultdict(set)
    inside_days: dict = defaultdict(set)
    clock: Counter = Counter()

    for index, symbol in enumerate(symbols, start=1):
        for path in sorted((root / symbol).glob(f"{symbol}_*.parquet")):
            table = pq.read_table(path, columns=["trade_date", "stamp"])
            stamps = table.column("stamp")
            minutes = pc.add(pc.multiply(pc.hour(stamps), 60), pc.minute(stamps))
            outside = pc.or_(pc.less(minutes, OPEN_MINUTE), pc.greater(minutes, LAST_MINUTE))
            days = table.column("trade_date")
            for day in set(days.filter(outside).to_pylist()):
                per_symbol[symbol] += 1
                per_day[day].add(symbol)
            for day in set(days.filter(pc.invert(outside)).to_pylist()):
                inside_days[day].add(symbol)
            for value in minutes.filter(outside).to_pylist():
                clock[f"{value // 60:02d}:{value % 60:02d}"] += 1
        print(f"  scanned {index}/{len(symbols)}: {symbol}", flush=True)

    muhurat = [day for day in sorted(per_day) if not inside_days.get(day)]
    mixed = [day for day in sorted(per_day) if inside_days.get(day)]

    lines = [
        "# chunk 9B -- out-of-session 1-minute stamps in the frozen store (QUESTIONS.md Q-17)",
        "",
        "Generated by `docs/evidence/chunk9b_out_of_session.py`, committed under CLAUDE.md's",
        "evidence rule (REVIEW_7 finding C3). Read-only, offline. Regenerate with:",
        "",
        "    python docs/evidence/chunk9b_out_of_session.py --out docs/evidence/chunk9b_out_of_session.md",
        "",
        "## Totals",
        "",
        f"* settled symbols scanned: **{len(symbols)}**",
        f"* symbol-days carrying at least one stamp outside 09:15..15:29: **{sum(per_symbol.values()):,}**",
        f"* distinct dates touched: **{len(per_day)}**",
        f"* dates where NO symbol has an in-session bar (the Muhurat shape, which CONTEXT 7-E2's",
        f"  date-level detector already excludes): **{len(muhurat)}** -- "
        + ", ".join(day.isoformat() for day in muhurat),
        f"* dates that MIX in-session and out-of-session bars (the shape that crashed the run):",
        f"  **{len(mixed)}**, covering **{sum(len(per_day[d]) for d in mixed):,}** symbol-days",
        "",
        "## By clock time (top 20)",
        "",
        "| stamp | bars |",
        "|---|---|",
    ]
    for stamp, count in clock.most_common(20):
        lines.append(f"| {stamp} | {count:,} |")
    lines += [
        "",
        "## The market-wide mixed dates (20 or more symbols affected)",
        "",
        "| date | symbols affected | symbols with data that day |",
        "|---|---|---|",
    ]
    for day in mixed:
        if len(per_day[day]) >= 20:
            lines.append(
                f"| {day} | {len(per_day[day])} | {len(inside_days[day])} |"
            )
    lines += [
        "",
        "## The per-symbol concentrations (top 15)",
        "",
        "| symbol | affected symbol-days |",
        "|---|---|",
    ]
    for symbol, count in per_symbol.most_common(15):
        lines.append(f"| {symbol} | {count} |")
    lines.append("")

    text = "\n".join(lines)
    print(text)
    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text + "\n", encoding="utf-8", newline="\n")
        print(f"\nwrote {out}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
