"""Q-20 evidence: the vendor's instrument master gives a symbol DIFFERENT ticks day to day.

Committed under CLAUDE.md's evidence rule. Regenerate with:

    python docs/evidence/chunk9b_master_tick_drift.py --out docs/evidence/chunk9b_master_tick_drift.md

OFFLINE and READ-ONLY: it opens the two instrument-master snapshots already sitting in
`cache_root/instrument_master/` and compares them. It fetches nothing and decides nothing.

WHY THIS EXISTS. CONTEXT 3.3 takes ``tickSize`` per symbol from the instrument master and
CONTEXT 4.3 calls that master a DAILY LIVE DUMP. Two snapshots are cached on this machine --
the one runbook step 3 pulled for the Q-18 rebuild (2026-07-31) and one the T4 re-fetch pulled
two days later (2026-08-02). ``latest_cached_master`` hands the run the NEWER one.

The tick is load-bearing and its failure mode is SILENT. CONTEXT 3.3 builds the volume-profile
row grid as ``totalTicks = round((top - bottom) / tick)``, so a different tick is a different
grid, a different POC, and therefore a different entry, stop and target -- and the code looks
right and returns a plausible price either way. That is exactly what REVIEW_0 measured for
QUESTIONS.md Q-2: with a hardcoded 0.05 tick the frozen calibration matched 15 of 25 days, and
every DIXON day was wrong by Rs 0.87 to Rs 78.

This script measures the disagreement. It does NOT rule on it -- QUESTIONS.md Q-20 puts that
to the architect.

Source files in this repo are ASCII-only on purpose (see src/acumen/config.py).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO / "src") not in sys.path:
    sys.path.insert(0, str(REPO / "src"))

from acumen import backtest as bt  # noqa: E402
from acumen.config import load_config  # noqa: E402
from acumen.instrument_master import CACHE_SUBDIR, load_master_file  # noqa: E402

SEALED_UNIVERSE = REPO / "docs" / "recovery" / "sealed_universe_210.json"
EQ_SUFFIX = "-EQ"


def sealed_symbols() -> list[str]:
    raw = json.loads(SEALED_UNIVERSE.read_text(encoding="utf-8"))
    return sorted({row["symbol"] for row in raw["data"]["UnderlyingList"]})


def raw_rows(path: Path, symbol: str) -> list[dict]:
    rows = json.loads(path.read_text(encoding="utf-8"))
    target = f"{symbol.upper()}{EQ_SUFFIX}"
    return [
        row
        for row in rows
        if str(row.get("exch_seg", "")).strip().upper() == "NSE"
        and str(row.get("symbol", "")).strip().upper() == target
    ]


def run(out_path: Path | None) -> int:
    config = load_config(include_env=False)
    home = config.path("cache_root") / CACHE_SUBDIR
    snapshots = sorted(home.glob("OpenAPIScripMaster_*.json"))
    if len(snapshots) < 2:
        print(f"Need two cached masters under {home}; found {len(snapshots)}.")
        return 2
    older, newer = snapshots[0], snapshots[-1]
    a, b = load_master_file(older), load_master_file(newer)
    symbols = sealed_symbols()

    register = bt.load_residual_register(
        config.path("data_root") / bt.RESIDUAL_LEDGER_RELPATH
    )
    settled = {s for s, e in register.items() if e.status == "settled"}

    moved: list[tuple[str, int, int, bool, int, int]] = []
    for symbol in symbols:
        left, right = a.by_symbol.get(symbol), b.by_symbol.get(symbol)
        if left is None or right is None:
            continue
        if left.tick_size_paise != right.tick_size_paise:
            moved.append((
                symbol,
                left.tick_size_paise,
                right.tick_size_paise,
                symbol in settled,
                len(raw_rows(older, symbol)),
                len(raw_rows(newer, symbol)),
            ))

    tokens_moved = [
        symbol
        for symbol in symbols
        if (a.by_symbol.get(symbol) and b.by_symbol.get(symbol))
        and a.by_symbol[symbol].token != b.by_symbol[symbol].token
    ]

    lines = [
        "# Q-20 evidence -- the instrument master's tick is not stable day to day",
        "",
        "Generated by `docs/evidence/chunk9b_master_tick_drift.py`, committed under CLAUDE.md's",
        "evidence rule. Offline, read-only, decides nothing (QUESTIONS.md Q-20 is the question).",
        "",
        f"- older snapshot : `{older.name}` -- {len(a.by_symbol):,} NSE-EQ instruments "
        "(runbook step 3, the master the Q-18 rebuild ran under)",
        f"- newer snapshot : `{newer.name}` -- {len(b.by_symbol):,} NSE-EQ instruments "
        "(pulled by the T4 re-fetch two days later; this is the one `latest_cached_master` "
        "hands the run)",
        f"- compared over  : the SEALED universe, {len(symbols)} symbols "
        "(`docs/recovery/sealed_universe_210.json`)",
        "",
        f"## {len(moved)} sealed symbols carry a DIFFERENT tick in the two snapshots",
        "",
        "`rows` is the number of NSE `-EQ` rows the raw master carries for that symbol in each",
        "snapshot. Both are 1 everywhere below, so this is **not** a selection artefact: the",
        "vendor publishes one row per symbol and simply states a different `tick_size` in it.",
        "",
        "| Symbol | older tick | newer tick | ratio | walked by the run? | rows older / newer |",
        "|---|---|---|---|---|---|",
    ]
    for symbol, old_tick, new_tick, is_settled, rows_a, rows_b in moved:
        lines.append(
            f"| {symbol} | {old_tick}p | {new_tick}p | x{new_tick / old_tick:g} | "
            f"{'**yes, settled**' if is_settled else 'no (quarantined)'} | {rows_a} / {rows_b} |"
        )
    walked = sum(1 for row in moved if row[3])
    lines += [
        "",
        f"**{walked} of the {len(moved)} are SETTLED**, i.e. inside the 204-symbol universe the",
        "chunk-9B run walks.",
        "",
        f"- tokens changed over the sealed universe: {', '.join(tokens_moved) or '**none**'}",
        f"- symbols absent from either snapshot: "
        f"{', '.join(s for s in symbols if s not in a.by_symbol or s not in b.by_symbol) or '**none**'}",
        "",
        "## What it means, and what it does not",
        "",
        "It does NOT mean a store is damaged: both snapshots are intact vendor files and the",
        "parser reads each correctly. It means CONTEXT 3.3's tick INPUT is not a fixed quantity",
        "on this machine -- re-running the same backtest two days apart would build a different",
        "row grid for these symbols, and CONTEXT 3.3's POC would move with it, silently.",
        "",
        "The run manifest already RECORDS which master a run used, by filename. Nothing PINS",
        "it. Which snapshot a historical backtest must use is unanswered by CONTEXT.md, so the",
        "chunk-9B RESUME-1 session refused to choose and raised **QUESTIONS.md Q-20**.",
        "",
    ]
    text = "\n".join(lines) + "\n"
    print(text)
    if out_path is not None:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")
        print(f"written: {out_path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="chunk9b_master_tick_drift")
    parser.add_argument("--out", default=None)
    args = parser.parse_args(argv)
    return run(Path(args.out) if args.out else None)


if __name__ == "__main__":
    raise SystemExit(main())
