"""Q-18 runbook step-1 SMOKE -- re-derives every claim in `q18_smoke_bhavcopy.md`.

Committed beside its own output under CLAUDE.md's evidence rule (REVIEW_7 finding C3): a
session making claims from real store data commits the generating script and its output.

The FETCH itself is not done here -- it is the ordinary, already-committed chunk-2 command:

    python scripts/backfill_daily.py --from 2026-07-01 --to 2026-07-31 --allow-network

This script only READS what that left behind, offline, and prints the numbers the evidence
file quotes, so anyone can re-run it and check them:

    python docs/evidence/q18_smoke_bhavcopy.py
    python docs/evidence/q18_smoke_bhavcopy.py --out docs/evidence/q18_smoke_bhavcopy.md

Source files in this repo are ASCII-only on purpose (see src/acumen/config.py).
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

WINDOW_START = date(2026, 7, 1)
WINDOW_END = date(2026, 7, 31)

#: The one row the evidence quotes in full -- a real, recognisable symbol-day.
WITNESS_SYMBOL = "TCS"
WITNESS_DAY = date(2026, 7, 30)


def _store():
    try:
        from acumen.daily_store import DailyStore
    except ModuleNotFoundError:
        sys.path.insert(0, str(REPO_ROOT / "src"))
        from acumen.daily_store import DailyStore
    from acumen.config import load_config

    root = load_config(include_env=False).path("data_root") / "daily_store"
    return DailyStore.at(root), root


def lines() -> list[str]:
    store, root = _store()
    out: list[str] = []
    add = out.append

    add(f"store            : {root}")
    add(f"window           : {WINDOW_START} .. {WINDOW_END}")
    add("")

    summary = store.coverage_summary(WINDOW_START, WINDOW_END)
    add("LEDGER, after the smoke and after the --rebuild-ledger correction (QUESTIONS.md Q-19)")
    for key in ("attempted", "file-present", "confirmed-404", "error", "missing", "weekend_session"):
        add(f"  {key:<16}: {summary[key]}")
    pending = store.pending_dates(WINDOW_START, WINDOW_END)
    add(f"  pending         : {len(pending)}  {', '.join(d.isoformat() for d in pending)}")
    add("")

    coverage = store.coverage(WINDOW_START, WINDOW_END)
    present = coverage[coverage["outcome"] == "file-present"]
    add(f"INGESTED DATES   : {len(present)}")
    if not present.empty:
        first, last = min(present["trade_date"]), max(present["trade_date"])
        add(f"  span           : {first} .. {last}")
        add(f"  rows ingested  : {int(present['row_count'].sum()):,}")
        add(f"  source formats : {sorted(set(present['source_format']))}")
    add("")

    frame = store.daily(WITNESS_SYMBOL, WITNESS_DAY, WITNESS_DAY)
    add(f"WITNESS ROW      : {WITNESS_SYMBOL} {WITNESS_DAY} (CONTEXT 4.1 columns, integer paise)")
    if frame.empty:
        add("  NOT PRESENT -- the store does not carry this symbol-day")
    else:
        row = frame.iloc[0]
        add(f"  series         : {row['series']}   (Q-4 whitelist: the equity)")
        add(
            f"  OHLC (paise)   : O {int(row['open_paise']):,} / H {int(row['high_paise']):,} / "
            f"L {int(row['low_paise']):,} / C {int(row['close_paise']):,}"
        )
        add(f"  volume         : {int(row['volume']):,}")
        add(f"  source format  : {row['source_format']}")
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Q-18 step-1 smoke evidence")
    parser.add_argument("--out", default=None, help="also write a markdown file")
    args = parser.parse_args(argv)

    body = lines()
    for line in body:
        print(line, flush=True)

    if args.out is not None:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            "\n".join(
                [
                    "# Q-18 runbook step 1 -- the one-month bhavcopy SMOKE",
                    "",
                    "Generated by `docs/evidence/q18_smoke_bhavcopy.py`, committed under",
                    "CLAUDE.md's evidence rule. The fetch was the ordinary chunk-2 command:",
                    "",
                    "    python scripts/backfill_daily.py --from 2026-07-01 --to 2026-07-31 --allow-network",
                    "",
                    "which ran to completion in 1m18s at 1 request / 2s: **31 dates attempted, 22",
                    "file-present, 9 confirmed-404, 0 errors**. One of those 404s was 2026-07-31",
                    "itself -- today, mid-session -- which under the Q-3 ruling would have been a",
                    "phantom holiday; it was un-recorded with `--rebuild-ledger` and raised as",
                    "**QUESTIONS.md Q-19**. Everything below is measured from the store afterwards,",
                    "offline and read-only.",
                    "",
                    "```",
                    *body,
                    "```",
                    "",
                ]
            ),
            encoding="utf-8",
            newline="\n",
        )
        print(f"\nwrote {out}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
