"""REVIEW_9B_REPORT: the per-symbol table and the register's own figures, re-derived.

Written by the chunk-9B REPORT REVIEW session (06-Aug-2026). Imports nothing from `src/acumen`.

Three things it checks, all of them things CONTEXT 4.6 makes a chunk-9 DUTY:

1. the report's `price-proven` column against the disclosed-residual register's own numbers,
   read from `<data_root>/universe_backfill/ledger.json` directly;
2. the B149 caveat, character for character, against the register entries it quotes;
3. the run-wide coverage figure (409,205 / 93.9317%) that CONTEXT 4.6 v1.6 carries.

    python docs/evidence/review9b_register_and_symbols.py

Source files in this repo are ASCII-only on purpose (see src/acumen/config.py).
"""

from __future__ import annotations

import json
import re
from fractions import Fraction
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DATA_ROOT = Path("C:/Users/chinm/acumen-data")
REGISTER = DATA_ROOT / "universe_backfill" / "ledger.json"
RUN_DIR = DATA_ROOT / "backtests" / "chunk9b_full"
REPORT = REPO / "docs" / "reports" / "chunk9b_backtest_report.md"
OUT = REPO / "docs" / "evidence" / "review9b_register_and_symbols.md"


def main() -> int:
    register = json.load(REGISTER.open(encoding="utf-8"))["symbols"]
    manifest = json.loads(RUN_DIR.joinpath("manifest.json").read_bytes().decode("utf-8"))
    universe = sorted(manifest["universe"])
    report = REPORT.read_text(encoding="utf-8")

    # --- the per-symbol table, parsed out of the report ---------------------------------------
    rows: dict[str, tuple[str, str]] = {}
    for line in report.splitlines():
        if not line.startswith("| ") or line.count("|") != 11:
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if cells[0] in register and cells[-1] in ("settled", "quarantined"):
            rows[cells[0]] = (cells[-2], cells[-1])

    lines: list[str] = []
    add = lines.append
    add("# REVIEW_9B_REPORT -- the register, the per-symbol coverage column and the B149 caveat")
    add("")
    add("Generated by `docs/evidence/review9b_register_and_symbols.py`, which imports NOTHING")
    add("from `src/acumen`. CONTEXT 4.6 makes reading the disclosed-residual register a chunk-9")
    add("duty *before any per-symbol statistic*; this checks that the duty was discharged with")
    add("the register's OWN numbers rather than with a recollection of them.")
    add("")
    add(f"* register `{REGISTER}` -- {len(register)} symbols")
    add(f"* run universe -- {len(universe)} symbols")
    add(f"* per-symbol rows parsed out of the report's section 9 -- **{len(rows)}**")
    add("")

    mismatched: list[str] = []
    missing: list[str] = []
    for symbol in universe:
        if symbol not in rows:
            missing.append(symbol)
            continue
        entry = register[symbol]
        total = entry["gate1p_total"]
        passed = entry["gate1p_pass"]
        exact = Fraction(passed, total) if total else Fraction(0)
        scaled = exact * 10000
        q, r = divmod(scaled.numerator, scaled.denominator)
        if r * 2 >= scaled.denominator:
            q += 1
        mine = f"{q // 100}.{q % 100:02d}%"
        theirs, status = rows[symbol]
        if mine != theirs or status != entry["status"]:
            mismatched.append(f"{symbol}: mine {mine}/{entry['status']} vs report {theirs}/{status}")

    add("## 1. Every symbol's price-proven percentage, recomputed from the register")
    add("")
    add(f"* symbols in the universe with no row in the report's table: **{len(missing)}** "
        f"{missing if missing else ''}")
    add(f"* rows whose price-proven percentage or register status DISAGREES with the register: "
        f"**{len(mismatched)}**")
    for text in mismatched[:20]:
        add(f"  * {text}")
    add("")
    add("The ten lowest-coverage symbols, from the register:")
    add("")
    add("| Symbol | gate1P pass | gate1P total | price-proven (mine) | report | status |")
    add("|---|---:|---:|---:|---:|---|")
    ranked = sorted(
        universe,
        key=lambda s: Fraction(register[s]["gate1p_pass"], register[s]["gate1p_total"] or 1),
    )
    for symbol in ranked[:10]:
        entry = register[symbol]
        exact = Fraction(entry["gate1p_pass"], entry["gate1p_total"])
        scaled = exact * 10000
        q, r = divmod(scaled.numerator, scaled.denominator)
        if r * 2 >= scaled.denominator:
            q += 1
        add(f"| {symbol} | {entry['gate1p_pass']:,} | {entry['gate1p_total']:,} | "
            f"{q // 100}.{q % 100:02d}% | {rows.get(symbol, ('-', '-'))[0]} | "
            f"{entry['status']} |")
    add("")

    # --- 2. the B149 caveat --------------------------------------------------------------------
    add("## 2. The B149 caveat, character for character")
    add("")
    caveat = manifest["residual_register"]["caveat"]
    add(f"* the manifest's caveat appears in the report VERBATIM: "
        f"**{caveat in report}**")
    add(f"* quoted: `{caveat}`")
    for symbol in ("IOC", "TATASTEEL"):
        entry = register[symbol]
        exact = Fraction(entry["gate1p_pass"], entry["gate1p_total"]) * 10000
        q, r = divmod(exact.numerator, exact.denominator)
        if r * 2 >= exact.denominator:
            q += 1
        add(f"* {symbol}: register says {entry['gate1p_pass']:,} of {entry['gate1p_total']:,} "
            f"= **{q // 100}.{q % 100:02d}%**, status `{entry['status']}`; the caveat's own "
            f"figure appears in it: **{f'{q // 100}.{q % 100:02d}%' in caveat}**")
    add("")

    # --- 3. run-wide coverage -------------------------------------------------------------------
    add("## 3. Run-wide coverage, from the register's own rows -- and the word `price-proven`")
    add("")

    def share(n: int, d: int, places: int = 4) -> str:
        exact = Fraction(n, d) * 10 ** (places + 2)
        q, r = divmod(exact.numerator, exact.denominator)
        if r * 2 >= exact.denominator:
            q += 1
        text = f"{q:0{places + 1}d}"
        return f"{int(text[:-places]):,}.{text[-places:]}%"

    settled_rows = [e for e in register.values() if e["status"] == "settled"]
    all_total = sum(e["gate1p_total"] for e in register.values())
    settled_total = sum(e["gate1p_total"] for e in settled_rows)
    add("| Reading | Numerator | Denominator | Coverage |")
    add("|---|---:|---:|---:|")
    add(f"| all three gates, SETTLED symbols / WHOLE lake -- **CONTEXT 4.6 v1.6's own figure, "
        f"and the report's** | {sum(e['usable_pass'] for e in settled_rows):,} | "
        f"{all_total:,} | "
        f"**{share(sum(e['usable_pass'] for e in settled_rows), all_total)}** |")
    add(f"| all three gates, whole lake / whole lake | "
        f"{sum(e['usable_pass'] for e in register.values()):,} | {all_total:,} | "
        f"{share(sum(e['usable_pass'] for e in register.values()), all_total)} |")
    add(f"| all three gates, settled / settled | "
        f"{sum(e['usable_pass'] for e in settled_rows):,} | {settled_total:,} | "
        f"{share(sum(e['usable_pass'] for e in settled_rows), settled_total)} |")
    add(f"| **gate 1P ONLY** (what section 9's column measures), settled / settled | "
        f"{sum(e['gate1p_pass'] for e in settled_rows):,} | {settled_total:,} | "
        f"{share(sum(e['gate1p_pass'] for e in settled_rows), settled_total)} |")
    add(f"| gate 1P ONLY, whole lake | "
        f"{sum(e['gate1p_pass'] for e in register.values()):,} | {all_total:,} | "
        f"{share(sum(e['gate1p_pass'] for e in register.values()), all_total)} |")
    add("")
    add(f"* **CONTEXT 4.6 v1.6's `409,205 = 93.9317%` reproduces EXACTLY** from the register's "
        f"own `usable_pass` summed over the 204 SETTLED symbols "
        f"({sum(e['usable_pass'] for e in settled_rows):,}) over the WHOLE lake's stored days "
        f"({all_total:,}). The report's section 11b quotes it correctly.")
    add(f"* settled **{len(settled_rows)}** / quarantined "
        f"**{sum(1 for e in register.values() if e['status'] == 'quarantined')}** "
        f"(CONTEXT 4.6: 204 / 6); rows whose status is neither: "
        f"**{sum(1 for e in register.values() if e['status'] not in ('settled', 'quarantined'))}**")
    add("* **BUT the report uses one word for two different quantities.** Section 1 calls "
        "93.9317% *price-proven* and glosses it as days *whose 1-minute prices cannot be "
        "reconciled against the exchange's own bhavcopy* -- which is gate 1P. It is not: it is "
        "the ALL-THREE-GATES figure, with a settled-only numerator over a whole-lake "
        "denominator. Section 9 then defines `price-proven` as gate 1P alone, per symbol. On "
        "gate 1P alone the settled universe is "
        f"{share(sum(e['gate1p_pass'] for e in settled_rows), settled_total)} proven, not "
        "93.9317%. No number is wrong and the direction is the conservative one, but the two "
        "uses collide on one page and a reader who averages section 9's column will not get "
        "section 1's headline.")
    add("")

    # --- 4. the Q-21(b) concentration table ---------------------------------------------------
    add("## 4. The Q-21(b) concentration, recounted from the ledger's flags")
    add("")
    flag = ("rule-3 minute scan met a D-1 that fails the CONTEXT 4.5/4.6 gate battery "
            "(QUESTIONS.md Q-21(b))")
    counts: dict[str, int] = {}
    with RUN_DIR.joinpath("ledger.jsonl").open("r", encoding="utf-8") as handle:
        for line in handle:
            if flag not in line:
                continue
            row = json.loads(line)
            if flag in row["flags"]:
                counts[row["symbol"]] = counts.get(row["symbol"], 0) + 1
    ordered = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    add(f"* total flagged rows: **{sum(counts.values())}** (report: 210)")
    add(f"* symbols carrying at least one: **{len(counts)}** (report: 59)")
    top6 = ordered[:6]
    share = Fraction(sum(n for _s, n in top6), sum(counts.values())) * 10000
    q, r = divmod(share.numerator, share.denominator)
    if r * 2 >= share.denominator:
        q += 1
    add(f"* the six largest carry **{sum(n for _s, n in top6)}** of them = "
        f"**{q // 100}.{q % 100:02d}%** (report: 47.14%)")
    add("")
    add("| Symbol | Rule-3 days refused on a battery-failing D-1 | Report |")
    add("|---|---:|---:|")
    claimed = {"IOC": 33, "GRASIM": 16, "TATASTEEL": 15, "OIL": 14, "TORNTPHARM": 11, "NMDC": 10}
    for symbol, n in top6:
        add(f"| {symbol} | {n} | {claimed.get(symbol, '-')} |")
    add("")
    OUT.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
